### ISSUE TITLE
Ubuntu packages

### ISSUE THREAD

**Issue by Fjodor42** [nextcloud/server-packages#4]
I'm not sure I understand DEB packaging well enough to actually undertake the task of becoming a maintainer, but what would I need to be aware of re copyright, if I were to make a PR with the contents of debian/ for the source packages of owncloud (dependency packages) and owncloud-files (actual owncloud) for others to tinker with to get nextcloud packaged?

I have those for OC 9.1.0, and would also be willing to 'sed' owncloud to nextcloud and adjust the version strings, but I'm not sure I would be comfortable with doing very much more, until someone has verified or denied that the approach taken by OC towards DEB packages, would also be of use for nextcloud...

**Comment by synchrone** [comment]
According to the [old sources](https://build.opensuse.org/package/view_file/isv:ownCloud:community/owncloud/debian.copyright?expand=1), they were GPL-licensed.

I am not sure about the packaging sources for owncloud-server 8.2 and above, since ownCloud has moved to it's own Build Service, but those old packaging scripts can totally be forked as per GPL terms.

**Comment by srbaker** [comment]
The debianization of owncloud is not terribly useful because of its age. I am already working on Debianizing Nextcloud 11, and will share my work.

**Comment by Fjodor42** [comment]
@srbaker: That sounds very good to me - I shall proceed to close this issue, then. Thank you for the heads-up!
